pub const ALLOWED_FONTS: [&str; 194] = [
    "Al Nile",
    "Al Tarikh",
    "American Typewriter",
    "Andale Mono",
    "Apple Braille",
    "Apple Braille Outline 6 Dot",
    "Apple Braille Outline 8 Dot",
    "Apple Braille Pinpoint 6 Dot",
    "Apple Braille Pinpoint 8 Dot",
    "Apple Color Emoji",
    "AppleGothic",
    "AppleMyungjo",
    "AppleSDGothicNeo",
    "Apple Symbols",
    "Arial",
    "Arial Black",
    "Arial Bold",
    "Arial Bold Italic",
    "ArialHB",
    "Arial Italic",
    "Arial Narrow",
    "Arial Narrow Bold",
    "Arial Narrow Bold Italic",
    "Arial Narrow Italic",
    "Arial Rounded Bold",
    "Arial Unicode",
    "Avenir Next",
    "Avenir Next Condensed",
    "Ayuthaya",
    "Baghdad",
    "Bangla MN",
    "Bangla Sangam MN",
    "Baskerville",
    "Beirut",
    "Bodoni Ornaments",
    "Chalkboard",
    "ChalkboardSE",
    "Chalkduster",
    "Cochin",
    "Comic Sans MS",
    "Comic Sans MS Bold",
    "Copperplate",
    "Corsiva",
    "Courier New",
    "Courier New Bold",
    "Courier New Bold Italic",
    "Courier New Italic",
    "Damascus",
    "DecoTypeNaskh",
    "DevanagariMT",
    "Devanagari Sangam MN",
    "Didot",
    "Diwan Kufi",
    "Diwan Thuluth",
    "EuphemiaCAS",
    "Farah",
    "Farisi",
    "Fira Code Bold Nerd Font Complete",
    "Fira Code Bold Nerd Font Complete Mono",
    "Fira Code Bold Nerd Font Complete Mono Windows Compatible",
    "Fira Code Bold Nerd Font Complete Windows Compatible",
    "Fira Code Light Nerd Font Complete",
    "Fira Code Light Nerd Font Complete Mono",
    "Fira Code Light Nerd Font Complete Mono Windows Compatible",
    "Fira Code Light Nerd Font Complete Windows Compatible",
    "Fira Code Medium Nerd Font Complete",
    "Fira Code Medium Nerd Font Complete Mono",
    "Fira Code Medium Nerd Font Complete Mono Windows Compatible",
    "Fira Code Medium Nerd Font Complete Windows Compatible",
    "Fira Code Regular Nerd Font Complete",
    "Fira Code Regular Nerd Font Complete Mono",
    "Fira Code Regular Nerd Font Complete Mono Windows Compatible",
    "Fira Code Regular Nerd Font Complete Windows Compatible",
    "Fira Code Retina Nerd Font Complete",
    "Fira Code Retina Nerd Font Complete Mono",
    "Fira Code Retina Nerd Font Complete Mono Windows Compatible",
    "Fira Code Retina Nerd Font Complete Windows Compatible",
    "Fira Code SemiBold Nerd Font Complete",
    "Fira Code SemiBold Nerd Font Complete Mono",
    "Fira Code SemiBold Nerd Font Complete Mono Windows Compatible",
    "Fira Code SemiBold Nerd Font Complete Windows Compatible",
    "Galvji",
    "GeezaPro",
    "Geneva",
    "Georgia",
    "Georgia Bold",
    "Georgia Bold Italic",
    "Georgia Italic",
    "GillSans",
    "GujaratiMT",
    "Gujarati Sangam MN",
    "Gurmukhi",
    "Gurmukhi MN",
    "Gurmukhi Sangam MN",
    "Helvetica",
    "HelveticaNeue",
    "Herculanum",
    "Hoefler Text",
    "Hoefler Text Ornaments",
    "Impact",
    "InaiMathi-MN",
    "Iosevka",
    "Kailasa",
    "Kannada MN",
    "Kannada Sangam MN",
    "Kefa",
    "Khmer MN",
    "Khmer Sangam MN",
    "Kohinoor",
    "KohinoorBangla",
    "KohinoorGujarati",
    "KohinoorTelugu",
    "Kokonor",
    "Krungthep",
    "KufiStandardGK",
    "Lao MN",
    "Lao Sangam MN",
    "LucidaGrande",
    "Luminari",
    "Malayalam MN",
    "Malayalam Sangam MN",
    "Menlo",
    "Microsoft Sans Serif",
    "Mishafi",
    "Mishafi Gold",
    "Monaco",
    "Mshtakan",
    "MuktaMahee",
    "Muna",
    "Myanmar MN",
    "Myanmar Sangam MN",
    "Nadeem",
    "NewPeninimMT",
    "NISC18030",
    "NotoNastaliq",
    "NotoSansBatak-Regular",
    "NotoSansKannada",
    "NotoSansMyanmar",
    "NotoSansNKo-Regular",
    "NotoSansOriya",
    "NotoSansTagalog-Regular",
    "NotoSerifMyanmar",
    "Optima",
    "Oriya MN",
    "Oriya Sangam MN",
    "Palatino",
    "Papyrus",
    "PingFang",
    "PlantagenetCherokee",
    "PTMono",
    "PTSans",
    "PTSerif",
    "PTSerifCaption",
    "Raanana",
    "Rockwell",
    "Sana",
    "Sathu",
    "Shree714",
    "Silom",
    "Sinhala MN",
    "Sinhala Sangam MN",
    "Skia",
    "SnellRoundhand",
    "Songti",
    "STIXTwoMath",
    "STIXTwoText-Italic",
    "STIXTwoText",
    "Symbol",
    "Tahoma",
    "Tahoma Bold",
    "Tamil MN",
    "Telugu MN",
    "Telugu Sangam MN",
    "Thonburi",
    "Times New Roman",
    "Times New Roman Bold",
    "Times New Roman Bold Italic",
    "Times New Roman Italic",
    "Trattatello",
    "Trebuchet MS",
    "Trebuchet MS Bold",
    "Trebuchet MS Bold Italic",
    "Trebuchet MS Italic",
    "Verdana",
    "Verdana Bold",
    "Verdana Bold Italic",
    "Verdana Italic",
    "Waseem",
    "Webdings",
    "Wingdings",
    "Wingdings 2",
    "Wingdings 3",
    "ZapfDingbats",
    "Zapfino",
];
